### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by loinsir** [29th-WE-SOPT-iOS-Part/KimInHwan#11]
## 📌  Feature Issue

데이터 연결 심화, UIGestureRecognizer

## 📝  To-do

- [ ] ImageView에 TapGestureRecognizer를 넣어서 ImageView가 tap되었을 때 action을 할 수 있도록 추가
- [ ] ImageView가 tap되었을 때 플레이 화면으로 present되도록 화면전환. 화면 전환시 데이터 전달
- [ ] 취소 버튼 누를 경우 플레이 화면 dismiss
