### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by loinsir** [29th-WE-SOPT-iOS-Part/KimInHwan#8]
## 📌  Feature Issue

4차 과제는 처음 만들었던 로그인 회원가입에 실제 API를 붙여보는 과제입니다.

## 📝  To-do

- [x] 시작 스토리보드를 변경하여 youtube home 화면이 처음으로 앱 빌드 했을때 보여질 화면으로 설정
- [x] 상단에 프로필을 눌렀을 때 로그인 flow로 넘어갈 수 있도록 화면 전환을 연결
- [x] 로그인 화면에서 다음 버튼을 누르면 서버통신을 하고 message로 alert를 띄우기
- [x] 로그인 시도시 각 상황에 다르게 화면전환을 할 수 있도록 구현하기
- [x] [도전과제] 로그인할 때 받는 결과값중 name값을 UserDefaults에 저장한 후 확인 화면에서 값을 활용하여 화면에 띄우기
